### ISSUE TITLE
Şehir isminin undefined gelmesi

### ISSUE THREAD

**Issue by harundogdu** [aligencay/weather-app#3]
Bir şehri aratıp, ardından input'u temizleyip aratınca, aşağıdaki şehir ismi alanı undefined geliyor.

![image](https://github.com/aligencay/weather-app/assets/43449361/884534ac-2a79-4638-9e7e-f078fc77dfa2)

**Comment by aligencay** [comment]
Sorun düzeltildi, ayrıca arama kısmına bir giriş yapılmadığında buna uygun error mesajının verilmesi sağlandı.
